### ISSUE TITLE
May I ask if it actually trains a ControlNet and lora?

### ISSUE THREAD

**Issue by JAIST-Bai** [HighCWu/ControlLoRA#13]
Training the lora seems to require only a small amount of data, but the data you are using is very large, I guess it essentially involves training a ControlNet and then a LoRA right? (Please correct me if my understanding is wrong, thanks!)

**Comment by HighCWu** [comment]
The essence of lora is lightweight fine-tuning. It can be trained with less data because the original model itself has strong prior information. When the dataset is small, direct full fine-tuning can achieve the effect even without using lora. It’s just that the weight of full fine-tuning is relatively large, so people use it less now.
So controllora actually uses this model prior for fine-tuning, but additionally injects the spatial information of the control part.

**Comment by JAIST-Bai** [comment]
Thank you for the explanation. Also I have another question, it seems that ControlNet's weights file is not specified in the code, so the default is to train from the beginning right? In other words, there is no support for fine-tuning on an existing ControlNet ckpt?

**Comment by HighCWu** [comment]
Yes. ControlLoRA is a controling network with LoRA, not the LoRA of controlnet. If you want to fine-tune ControlNet using LoRA, you can mix the `diffusers` example codes about [training controlnet](https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet.py) and [training lora](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora.py).

**Comment by JAIST-Bai** [comment]
ok, thanks for your patience and explanation!
