### ISSUE TITLE
Are you using your controllora on a Lora model or a full model?

### ISSUE THREAD

**Issue by ninjasaid2k** [HighCWu/ControlLoRA#3]
Your output images are low in quality, is this because you are using a Lora trained stable diffusion model or are you using a full model?

**Comment by HighCWu** [comment]
> Your output images are low in quality, is this because you are using a Lora trained stable diffusion model or are you using a full model?

I think the main reason is the dataset. When canny was used as a guide, I used 5,000 pictures from diffusiondb as a dataset. This is a dataset generated from stable diffusion, which is not very real. When pose is used as a guide, I used 100 MPII images as a dataset, and the original images quality are relatively poor. Also, the size of the dataset I'm using is relatively small. 

Why am I using small amounts of data and poor quality datas? Because my main purpose is to verify the model. Also, I don't have many sources of datasets.

If you have enough datas, but still get poor results, you can try to adjust the parameters of ControlLora, I provide a lot of parameters to make your ControlLora bigger. You can create your own parameter configuration in the `configs` folder.

**Comment by HighCWu** [comment]
Also, each of my models was only trained for 3 hours on the 4080. I personally think that its fine-tuning results have exceeded my expectations

**Comment by HighCWu** [comment]
I'm thinking of training my model with more datas and longer training time

**Comment by HighCWu** [comment]
For the title question, ControlLora does not mean to control LoRa, but control the stable diffusion spatial information by a similar method like LoRA.
